### ISSUE TITLE
[FEATURE] Better error message when connection failed

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#100]
**Describe the bug**
The connection to   https://heasarc.gsfc.nasa.gov/xamin/vo/tap fails on a CORS locking

TapHandle does not switch on  the proxy
![Screenshot 2021-12-21 at 08 56 28](https://user-images.githubusercontent.com/11462648/146892542-d93ef4bb-5ffe-4e9c-8228-f554e5bb04e5.png)

**Expected behavior**
- The switch to the proxy mode must be transparent.
- If the connection cannot be followed to to redirection (see Chandra), an explicit message should be showed up suggesting to contact the admin.
- In any cases, the message `cannot connect` should come with some hypothesis or tips (look at a console, may be a CORS issue contact LM etc)

**Comment by galyfray** [comment]
The app does switch to the proxy, the proxy just failed to work due to redirection 
![Capture d’écran de 2022-01-03 11-04-55](https://user-images.githubusercontent.com/37240229/147918779-580543fd-0d2e-4c70-971f-1e7bf41bf359.png)
