### ISSUE TITLE
[Bug]Empty service

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#101]
**Describe the bug**
The connection to  http://hst.esac.esa.int/tap-server switches on  the proxy (contrary to #100) but shows up an empty service. 

![Screenshot 2021-12-21 at 09 05 06](https://user-images.githubusercontent.com/11462648/146893679-4f504029-3bfe-4e22-851e-1ffe063fe9a7.png)

Below is the query sent to TAP_SCHEMA:
![Screenshot 2021-12-21 at 09 07 27](https://user-images.githubusercontent.com/11462648/146893958-05bb5224-f37f-458e-a2ea-699c8a766f6a.png)

The query response looks OK 
![Screenshot 2021-12-21 at 09 06 36](https://user-images.githubusercontent.com/11462648/146893862-d4841f81-839e-4298-8aa8-6736a697601d.png)

There no warning in the console.

**Comment by galyfray** [comment]
I get a 404 when I try ...
