### ISSUE TITLE
[FEATURE]Better error message when tap service does not work

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#102]
**Is your feature request related to a problem? Please describe.**

The connection to `http://jvo.nao.ac.jp/skynode/do/tap/agn/` works well through the proxy by finally shows up a 
`can't connect to the select service`

The reason for this failure is that the query on the `TAP_SCHEMA` cannot be processed:
![Screenshot 2021-12-21 at 09 22 54](https://user-images.githubusercontent.com/11462648/146896113-97a529ba-1e73-46f4-a3d0-4752bea7869c.png)

These old TAP services based on skynode usually do not work, bu the user return must be improved in that case. 
The message is same as for a CORS blocking

**Describe the solution you'd like**
Display the query error message in the alert box

**Comment by galyfray** [comment]
related to #100
