### ISSUE TITLE
[FEATURE] Connecting without double JOIN

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#105]
Try to connect a service without running a double JOIN query on the TAP schema.
This would allow to connect the service at least on one table even the JOIN browsing fails

**Comment by lmichel** [comment]
When you clickclick on a Chandra table, you send the following query
```SQL
SELECT tap_schema.keys.from_table, tap_schema.keys.target_table,tap_schema.keys.key_id , tap_schema.key_columns.from_column, tap_schema.key_columns.target_column 
FROM tap_schema.keys
 JOIN tap_schema.key_columns ON tap_schema.keys.key_id = tap_schema.key_columns.key_id
JOIN tap_schema.tables ON  tap_schema.keys.from_table = tap_schema.tables.table_name
WHERE  tap_schema.tables.schema_name = 'csc2' OR  tap_schema.tables.schema_name = 'csc2'
```
The constraints in this double JOIN query are all related to the same table `schema_name ` (duplicated in this case ?)
The query might be split in 2 separate queries: one joining 

To be investigated with regards on the impact on the API

**Comment by lmichel** [comment]
One possible workaround would be to rise an alert when this failure occurs and to continue as if there were no joins.
`Joins keys can not be extracted from the TAP schema (see console) , table joins will be ignored`.

**Comment by galyfray** [comment]
>The constraints in this double JOIN query are all related to the same table schema_name (duplicated in this case ?)

yes this comes from a compatibility patch that try schema names with a without double quotes when there is no double quotes the constraint is duplicated this could be removed when unnecessary if ever needed.
>One possible workaround would be to rise an alert when this failure occurs and to continue as if there were no joins.
Joins keys can not be extracted from the TAP schema (see console) , table joins will be ignored.

I would rather create a static "testService" method in the api which would try different edge cases and return information such that support for "public".* (#106 ) support multiple joint etc then use this method when connecting and saving it's data to properly handle such behavior.

I see two main advantages of this over an alert :
 - We don't yell a the user that the service doesn't work as expected, very usefull if you use the API in the background and the end user has no choice over which service it connects to
 - The Devs have the ability to auto detect and handle this in there app
 
 This query can be separated in two queries but joining them will be needed in the API's code. 
 
 This should not affect too much the API as long as this king of problem doesn't occur on services with an incredible amount of joins.

**Comment by lmichel** [comment]
This idea of service testing come back from time to time and has never been properly implemented.
This is the good way to proceed.
If you are doing so, the result of that test (working capabilities) must be reported in the service info panel [i] or even better in the ![Screenshot 2022-01-05 at 14 53 05](https://user-images.githubusercontent.com/11462648/148228645-17a591c0-61aa-4c36-a08a-2e246d648749.png)
