### ISSUE TITLE
[FEATURE] Check whether a service support a quoted name for the schema public

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#106]
Some services, e.g. HEASARC (https://heasarc.gsfc.nasa.gov/xamin/vo/tap),  do not support query like 
```SQL
SELECT * FROM "public".xyz
```
This could be checked at connection time and stored as a service capability later used to write running queries

**Comment by galyfray** [comment]
I've just checked and it seems like we never use a `SELECT *` in the whole api is this worth checking even if we don't use it ?

**Comment by galyfray** [comment]
my bad that's about services which want us to use `public.xyz` instead of `"public".xyz` ...

**Comment by lmichel** [comment]
Some service require "public" some other require not to have it

**Comment by lmichel** [comment]
vu
