### ISSUE TITLE
[Bug]hst public schema not working

### ISSUE THREAD

**Issue by galyfray** [lmichel/TAP-complex-data#111]
When trying to see data from [hst](https://saada.unistra.fr/tapcomplex/app/Tap_Handle_MK2/taphandle.html?url=//hst.esac.esa.int/tap-server/tap)'s public.dual table an error occurs. 

This comes from three factor : 
- this is a `public` schema
- they store the table names as qualified tables names in theyre schema
- the qualified table name is not quotted

this lead the AttributeHolder object to go a bit crazy by not recognizing anything.

Here is the TODO list to properly fix this
 - handle when the Atrribute holder crash 
 - handle tables without any columns (may append never nows)
 - fix the Attribute holder to properly work this case

**Comment by lmichel** [comment]
vu

**Comment by lmichel** [comment]
vu
