### ISSUE TITLE
[Bug] Query for not updated

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#113]
**Describe the bug**
Open TapHandle on [caom](http://taphandle.astro.unistra.fr/tapcomplex/app/Tap_Handle_MK2/taphandle.html?url=//vao.stsci.edu/CAOMTAP/TapService.aspx)
Open table CaomObservation and play with it: everything is fine

Now, 
- set ` ucd: %instr.fov%` in the search bar and select `BIRA IASB`
- open the table `soir.epncore`
  - error in console: `Uncaught (in promise) ReferenceError: h3 is not defined`
  - The label on the query form does not change
  - The query form keeps empty

**Comment by galyfray** [comment]
already found and fixed in dev
