### ISSUE TITLE
[Bug] Search bas not working anymore !

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#121]
**Describe the bug**
The following error appears in the console (I justed a word e.g. gavo)
![Screenshot 2022-01-10 at 16 51 49](https://user-images.githubusercontent.com/11462648/148796183-781277ef-135f-4ba9-bcd0-1a5c1db517d9.png)

**Comment by galyfray** [comment]
same issue as #122 
due to a misspelled variable joins where no longer retrieved making the api unable to correctly build the requests ...

**Comment by lmichel** [comment]
vu
