### ISSUE TITLE
[FEATURE] Tracking function

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#124]
Create a global function that does nothing and that is called from the most important events processed (TBD):
```js
func trackAction (message) {
if server is taphandle {
    // does nothing
} else {
   //does nothing
}
```
Later on , this function will call a tracking function feeding the connection statistics

**Comment by galyfray** [comment]
what are the events that needs to be tracked ?

**Comment by lmichel** [comment]
at least:
- application launch
- service connection
- table opening
- query form send query
- table row click
- send samp message
- download

**Comment by galyfray** [comment]
action tracked : 
 - appllication launch
 - usage of url parameter
 - voTable send through SAMP
 - Query runned by form
 - Error raised to the attention of the user (silents error are not tracked)
 - service disconnect
 - service connection 
 - VOTable dowload
 - table row click
 - opening a sub table
 - opening a root table

**Comment by lmichel** [comment]
approved. If you want to test it you can add the piece of JS you can find on the Taphadle page

**Comment by lmichel** [comment]
There is an error in the query, Space in message seams not t be replaced with '+'
