### ISSUE TITLE
[Bug] No column found in table (but columns are detected)

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#125]
**Describe the bug**
url=https://casda.csiro.au/casda_vo_tools/tap

Open [here](https://taphandle.astro.unistra.fr/tapcomplex/app/Tap_Handle_MK2/taphandle.html?url=https://casda.csiro.au/casda_vo_tools/tap)

![Screenshot 2022-01-11 at 21 47 02](https://user-images.githubusercontent.com/11462648/149018980-1a44b06a-2957-4922-9962-2b1fd6ebc9e4.png)

Tables cannot be displayed although columns are shown in the [i] popup as well as in the query form.

**Comment by lmichel** [comment]
The pb amazingly occurs in the TAP_SCHEMA as well

**Comment by galyfray** [comment]
this comes from an error [414](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/414) the URL is too long for the server ... this service seems to use the tapxy we need to investigate if this comes from the tapxy or the service itself.

**Comment by lmichel** [comment]
L'erreur vient bien du server CSIRO:
```
curl 'http://casda.csiro.au/casda_vo_tools/tap/sync?query=SELECT%20tap_schema.keys.from_table%2C%20tap_schema.keys.target_table%2Ctap_schema.keys.key_id%20%2C%20tap_schema.key_columns.from_column%2C%20tap_schema.key_columns.target_column%20%0AFROM%20tap_schema.keys%0A%20JOIN%20tap_schema.key_columns%20ON%20tap_schema.keys.key_id%20%3D%20tap_schema.key_columns.key_id%0AJOIN%20tap_schema.tables%20ON%20%20tap_schema.keys.from_table%20%3D%20tap_schema.tables.table_name%0AWHERE%20%20tap_schema.tables.schema_name%20%3D%20%27casda%27%20OR%20%20tap_schema.tables.schema_name%20%3D%20%27casda%27&format=votable&lang=ADQL&request=doQuery' -L
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>414 Request-URI Too Long</title>
</head><body>
<h1>Request-URI Too Long</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
</p>
</body></html>

```

**Comment by lmichel** [comment]
Issue understood.
The service is declared in `https` but taphandle goes through the `tapxy` proxy which runs over `http`.
It should use `tapsxy` since the  service is in `https`

**Comment by lmichel** [comment]
vu
