### ISSUE TITLE
[FEATURE] Connecting a service that is not in the regostry

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#129]
When we put a service URL as a TapHandle URLK parameter, the search bar  is invoked to look for that service in the registry.
What happens if the service is not in the registry? 
Can we connect it anyway?

Same question for connecting a non regjstered service by putting a URL directly in the search bar;

**Comment by galyfray** [comment]
yes we can connect even if the service is not in the registry. When the search bar broke we could still use direct urls to connect
