### ISSUE TITLE
[FEATURE] Telling there is no subtable

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#133]
When the user click on a data row, the row gets yellow, but there it is not clear whether he/she can expect get get subtables or not.
The following behavior would help:
- Display subtables if there are ( as now)
- Show up an alert otherwise e.g. "No joined data"

**Comment by galyfray** [comment]
I am not sure that an alert is a good solution. alerts are very annoying.

**Comment by lmichel** [comment]
Users have to know why nothing comes up. You can either change the color: a  pale gray instead of yellow

**Comment by lmichel** [comment]
vu
