### ISSUE TITLE
[FEATURE] No way to change the number of selected row

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#144]
Need a selector in the query form, may be below the ADQL query, this would allow to change JSResource stuff

**Comment by galyfray** [comment]
the JsRessource test page had a slide for every tables allowing to select how many entries you want to query.
Re-using this way of doing it will be easier and more flexible for the end user allowing to change the setting for every table. 
should we go this way or the way you proposed ?

**Comment by galyfray** [comment]
well i am proposing to not put it on the query form like in the old jsResource test page 
![Screenshot_20220120_120223](https://user-images.githubusercontent.com/37240229/150326746-3a2da61a-3a95-4eb9-b1ba-bd3e6f2d3f39.png)
>The question is to decide where to put this widget in query form.

I have no good idea on that

**Comment by lmichel** [comment]
you could have a `Query [10] entries` similar to the `Show [10] entries`.
If you merge SAMP and download as suggested in https://github.com/lmichel/TAP-complex-data/issues/146, you ay save place
