### ISSUE TITLE
[FEATURE] Bibcode identification

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#151]
On //hst.esac.esa.int/tap-server/tap

Unrecognized pattern

![Screenshot 2022-01-26 at 13 18 41](https://user-images.githubusercontent.com/11462648/151161938-764d6097-9451-4a2d-9d84-eec7f0d8aa54.png)

**Comment by lmichel** [comment]
on //voparis-tap-planeto.obspm.fr/__system__/tap/run/tap

planets -> epn-core: bibcodes not recognized: e.g. `2018CeMDA.130...22A#2000asqu.book.....C`
Regexp to be extended `/.......(?:#[a-zA-Z.0-9]+)?$)` in format.js?

**Comment by galyfray** [comment]
the issue here was from the `conf` part it is supposed to be the volume number but it can also be a word ...

**Comment by lmichel** [comment]
apparently, keep the current working regexp commented anyway

**Comment by lmichel** [comment]
checked
