### ISSUE TITLE
[FEATURE] Knowledge tank improvement

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#155]
### part 1

The sections `longitude/latitiude` should be resolved before `position`
This is important for Vizier where reference coordinates are always given with `pos.eq.ra/dec`

**Comment by lmichel** [comment]
### Part 2

When a section cannot be resolved, it must be re-evaluated against the first words.
Ex, nothing matches the following condition:
```
 "brightness" : ["phys.luminosity;meta.main","phot.mag;meta.main","phys.flux;meta.main","phot.count;meta.main"],
```
The try again with 
```
 "brightness" : ["phys.luminosity","phot.mag","phys.flux","phot.count"],
```

**Comment by galyfray** [comment]
instead of adding an extra layer of complexity to the KT I have added the `"phys.luminosity","phot.mag","phys.flux","phot.count"` UCDs at the end of the brightness field. the effect should be the same.

**Comment by lmichel** [comment]
looks better
