### ISSUE TITLE
[FEATURE] More than 10 lines

### ISSUE THREAD

**Issue by galyfray** [lmichel/TAP-complex-data#35]
**Is your feature request related to a problem? Please describe.**
the API doesn't allow to select more than 10 lines

**Describe the solution you'd like**
being able to change this either by a specific methods or using another param in the method we call to gather the data

**Comment by lmichel** [comment]
## Root table

- A choice-list has to be added to the query form 
  - When the selected choice changes, a new query is run
- Another choice list is added to each sub-table
  -  When the selected choice changes, the new size is stored somewhere and the root table row selection action is triggered again
  - This feature will likely require an update of the map to add the query size along with the selected columns
