### ISSUE TITLE
[FEATURE]"smart" async of methods

### ISSUE THREAD

**Issue by galyfray** [lmichel/TAP-complex-data#64]
many methods use async await for a very small part of the work and sometimes asynchronous work isn't needed each call due to a cache it would make the api more flexible to make methods use a "smart" async: 
- new standard parameters among every api method : `fullAsync` when true the whole method is wraped into a promise (even if unnecessary)
- reduce the async part to only the needed 
- only return a promise when needed if work is entirely done with cached data it shouldn't create a promise
- add generic code to ease the handle of the "smart" async by the user ?

**Comment by lmichel** [comment]
What's happens if non async method call an API method with `fullAsync=false` and that method runs an async operation?

**Comment by galyfray** [comment]
the same as currently : things might go wrong
`fullAsync=false` means put the whole method in a `Promise` when set to false (the default) then the methods would run as much as possible without any async job but when needed use them. 
thus if a sync function run a currently asyn method like a query he will get a `Promise` as return object and how it ends would be quite the same from what would append now and what would append after the implementation of this.

**Comment by lmichel** [comment]
That supposes the caller to be informed on the risk for the called method to run in async

**Comment by galyfray** [comment]
which is already the case async methods are declared in the doc as async.
