### ISSUE TITLE
[FEATURE] ~Better~ encapsulation 

### ISSUE THREAD

**Issue by galyfray** [lmichel/TAP-complex-data#66]
In the current api implementation there is no encapsulation. If a true encapsulation is currently impossible in JS (or at least to hard to be worth) a basic encapsulation would probably be a good things to add. 

as classes are defined in [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) making a private method or attribute would be easy (define it inside the function and don't register it in the main object), even if this would require some tests to ensure that all objects doesn't share the sames private objects this remains an easy way to do.
Protected fields and methods could be registered in a `protected` field of the object, this is not a true protected field but this way would ensure that anyone messing with those fields and functions would know that he may not be supposed to do so.

**Comment by lmichel** [comment]
> In the current api implementation there is no encapsulation. If a true encapsulation is currently impossible in JS (or at least to hard to be worth) a basic encapsulation would probably be a good things to add.

Not agreed, there is nothing explicit for this but the JSResource pattern implements it properly.
I don't know how close it is from IIFE.

**Comment by lmichel** [comment]
IN some places the IIFE pattern is used, especially with singleton, You may look at basic.js.
