### ISSUE TITLE
[FEATURE] MLinify

### ISSUE THREAD

**Issue by lmichel** [lmichel/TAP-complex-data#92]
Minify code + style resources
- loading speed up
- Easier to embed in another application

**Comment by galyfray** [comment]
the minification of the API part still works just fine. minified  code can be produce using `npm run build` on the root folder of the github

**Comment by galyfray** [comment]
concerning the minification of the app a workflow has to be decided concerning the deployment of the app

**Comment by lmichel** [comment]
Just a clear README.md will be enough
